site_name: E-monitor
nav:
    - Вступ: index.md
    - Показники: parameters.md
    - Аналітика: analytics.md
    - Карта: map.md
    - Налаштування: settings.md
    - Керування: control.md
theme: readthedocs
lang: ru
